name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
    - uses: actions/checkout@v3
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build App
      run: dotnet build -c Release --no-restore 

    - name: Run automated test
      run: dotnet test -c Release --no-build
